### ISSUE TITLE
Patient creation form issue

### ISSUE THREAD

**Issue by Brick7Face** [Brick7Face/psychiatric-guide-app#100]
When trying to create a new patient and entering an invalid phone number (i.e. too long or has dashes), the page crashes with a form didn't validate error. So, we need some error checking that just doesn't let the user submit that instead of crashing.

Additionally, there is not a way to add/change medications to the patient other than through the admin site or population script.

**Comment by erynplant** [comment]
The phone number issue will be fixed by #109. Will create a new issue for the adding/changing medications, closing this one.
