### ISSUE TITLE
Signed in display issue

### ISSUE THREAD

**Issue by Brick7Face** [Brick7Face/psychiatric-guide-app#28]
The banner that says who the user is signed in as is blank, at least when signed in as admin. It just says "Signed in as: " when it probably should read "Signed in as: admin" or something like that.

**Comment by Brick7Face** [comment]
We should add an admin tag to all users. Next to their name we can just have (Admin), then if they don't have a name just display that tag.

**Comment by MadisonFichtner** [comment]
Fixed in treatment-overview branch
