### ISSUE TITLE
CSS font color error

### ISSUE THREAD

**Issue by AlexanderHarry** [Brick7Face/psychiatric-guide-app#36]
When clicking the side bar "Admin Actions" as an admin user, the font color for the drop down link that links to the create user page is the same color as the sidebar blue.

**Comment by AlexanderHarry** [comment]
This happens when the page is scaled down to the size of a mobile device.  Once expanded, everything is shown again.  Could be due to the icon?

**Comment by MadisonFichtner** [comment]
Same issue as one already opened. Closing.
