### ISSUE TITLE
Medication creation error checking

### ISSUE THREAD

**Issue by Brick7Face** [Brick7Face/psychiatric-guide-app#65]
Medication creation form should error check, for example the max dose should not be able to be less than the initial dose, etc.

**Comment by Brick7Face** [comment]
This particular issue is of lower priority as the prescriber would not be enter new medication information

**Comment by AlexanderHarry** [comment]
It is possible that the dose could be lowered for a patient.

**Comment by Brick7Face** [comment]
Right but that has to do with the patients current dosing, not the initial and maximum dose information for the medication itself

**Comment by erynplant** [comment]
Closing for now, not a bug
