### ISSUE TITLE
Need to be able to add more lines of notes in the edit patient form

### ISSUE THREAD

**Issue by erynplant** [Brick7Face/psychiatric-guide-app#79]
Need to be able to add more lines of notes in the edit patient form

**Comment by Brick7Face** [comment]
The current form shouldn't have a max length or anything - I'm guessing it just stopped allowing you to enter text after a while?

**Comment by erynplant** [comment]
![image](https://user-images.githubusercontent.com/11479899/55446324-5f9de600-557c-11e9-9817-4a4a841e553b.png)
Not sure what you mean, this is a lot of lines

**Comment by Brick7Face** [comment]
Oh okay, that looks like a lot of notes to me lol
